baseURL = "/"
languageCode = "en-us"
title = "主題示例站"
theme = "EarlGrey"

paginate = 5

[markup]
    [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
    [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
